{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolchain-probe/0.0.1/toolchain-probe-0.0.1.module",
    "group": "local.dyn4k.probe",
    "module": "toolchain-probe",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolchain-probe.aar",
          "url": "toolchain-probe-android-0.0.1.aar",
          "size": 1800,
          "sha512": "91f8a3852596eaba856d12c0d6cdd0559f5ce34ecfc0b8d1f13122e12e8f9c804203ac36cda61b5908275251afacd1921e24b2b26ae780622ad40e068f345965",
          "sha256": "5b6f0c5d65048c599e682cfb6ba2f988103ca23b3dc0dbd4b493f67df7168968",
          "sha1": "2de08b45b165f3a65940024505fc5a9154a4f5fd",
          "md5": "307da233ff93157f20bb4a236569b808"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolchain-probe.aar",
          "url": "toolchain-probe-android-0.0.1.aar",
          "size": 1800,
          "sha512": "91f8a3852596eaba856d12c0d6cdd0559f5ce34ecfc0b8d1f13122e12e8f9c804203ac36cda61b5908275251afacd1921e24b2b26ae780622ad40e068f345965",
          "sha256": "5b6f0c5d65048c599e682cfb6ba2f988103ca23b3dc0dbd4b493f67df7168968",
          "sha1": "2de08b45b165f3a65940024505fc5a9154a4f5fd",
          "md5": "307da233ff93157f20bb4a236569b808"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "toolchain-probe-android-0.0.1-sources.jar",
          "url": "toolchain-probe-android-0.0.1-sources.jar",
          "size": 695,
          "sha512": "92db3e2c2fc4660e7ed7d4a8676b2e579304040b77497d3cc3390f335fee329c84b0f13aaa7764fdd1d6fac3f29d806f8a951a668ad77b3118ae7f8b38915dad",
          "sha256": "5c50338bdd00dd7b98e8fd48f8fd972fc1dafc423532336e07e3adfb3dc52001",
          "sha1": "13a0eb1213fdba2cbda3458d47a038f151a8d72a",
          "md5": "1f0fea22ac07a92637cd13c0bea601d7"
        }
      ]
    }
  ]
}
